import { Business, Branch, Sale, InventoryItemSummary } from "@/types";

/**
 * ============================================================================
 * CHAMA POS - MOCK DATA SERVICE (PHASE 1 ONLY)
 * ============================================================================
 * NOTE: This mock data is strictly segregated from database services.
 * In Phase 2+, these will be replaced with server-side queries using
 * Mongoose models with strict tenant context.
 */

export const mockCurrentBusiness: Business = {
  _id: "biz_demo_001",
  name: "Chama Modzone",
  slug: "chama-modzone",
  industry: "car_accessories",
  ownerUserId: "usr_owner_001",
  email: "contact@chamamodzone.com",
  phone: "+94 11 234 5678",
  subscriptionTier: "BUSINESS",
  subscriptionStatus: "active",
  address: {
    street: "142 Galle Road",
    city: "Colombo",
    state: "Western Province",
    postalCode: "00300",
    country: "Sri Lanka",
  },
  settings: {
    currency: "USD",
    currencySymbol: "$",
    taxRate: 8,
    enableTaxes: true,
    receiptHeader: "Chama Modzone - Premium Car Audio & Performance",
    receiptFooter: "Thank you for upgrading your ride with us!",
    lowStockThresholdDefault: 5,
  },
  isActive: true,
  createdAt: new Date("2026-01-10T08:00:00Z"),
  updatedAt: new Date("2026-03-01T12:00:00Z"),
};

export const mockBranches: Branch[] = [
  {
    _id: "br_colombo_main",
    businessId: "biz_demo_001",
    name: "Colombo Main Flagship",
    code: "CMB-01",
    phone: "+94 11 234 5678",
    email: "colombo@chamamodzone.com",
    address: {
      street: "142 Galle Road",
      city: "Colombo",
      state: "Western",
      postalCode: "00300",
      country: "Sri Lanka",
    },
    isMain: true,
    isActive: true,
    createdAt: new Date("2026-01-10"),
    updatedAt: new Date("2026-01-10"),
  },
  {
    _id: "br_negombo",
    businessId: "biz_demo_001",
    name: "Negombo Auto Center",
    code: "NGB-02",
    phone: "+94 31 456 7890",
    email: "negombo@chamamodzone.com",
    address: {
      street: "88 Main Street",
      city: "Negombo",
      state: "Western",
      postalCode: "11500",
      country: "Sri Lanka",
    },
    isMain: false,
    isActive: true,
    createdAt: new Date("2026-02-15"),
    updatedAt: new Date("2026-02-15"),
  },
  {
    _id: "br_kandy",
    businessId: "biz_demo_001",
    name: "Kandy Express Branch",
    code: "KDY-03",
    phone: "+94 81 765 4321",
    email: "kandy@chamamodzone.com",
    address: {
      street: "12 Peradeniya Road",
      city: "Kandy",
      state: "Central",
      postalCode: "20000",
      country: "Sri Lanka",
    },
    isMain: false,
    isActive: true,
    createdAt: new Date("2026-03-01"),
    updatedAt: new Date("2026-03-01"),
  },
];

export interface DashboardMetrics {
  todaySalesTotal: number;
  todaySalesChangePercent: number;
  todayOrdersCount: number;
  todayOrdersChangePercent: number;
  totalProductsCount: number;
  lowStockItemsCount: number;
  totalCustomersCount: number;
  todayExpensesTotal: number;
}

export const mockDashboardMetrics: DashboardMetrics = {
  todaySalesTotal: 3485.5,
  todaySalesChangePercent: 14.8,
  todayOrdersCount: 38,
  todayOrdersChangePercent: 8.5,
  totalProductsCount: 842,
  lowStockItemsCount: 5,
  totalCustomersCount: 1290,
  todayExpensesTotal: 412.0,
};

export const mockRecentSales: (Sale & { branchName: string; itemCount: number })[] = [
  {
    _id: "sale_001",
    businessId: "biz_demo_001",
    branchId: "br_colombo_main",
    branchName: "Colombo Main Flagship",
    invoiceNumber: "INV-2026-0412",
    cashierUserId: "usr_cashier_01",
    cashierName: "Kasun Perera",
    customerId: "cust_101",
    customerName: "Rohan De Silva",
    itemCount: 3,
    items: [],
    subtotal: 420.0,
    discountTotal: 20.0,
    taxTotal: 32.0,
    grandTotal: 432.0,
    paidAmount: 432.0,
    changeAmount: 0.0,
    paymentMethod: "card",
    paymentStatus: "paid",
    status: "completed",
    createdAt: new Date(Date.now() - 15 * 60 * 1000), // 15 mins ago
    updatedAt: new Date(Date.now() - 15 * 60 * 1000),
  },
  {
    _id: "sale_002",
    businessId: "biz_demo_001",
    branchId: "br_negombo",
    branchName: "Negombo Auto Center",
    invoiceNumber: "INV-2026-0411",
    cashierUserId: "usr_cashier_02",
    cashierName: "Dinesh Fernando",
    customerId: "cust_102",
    customerName: "Walk-in Customer",
    itemCount: 1,
    items: [],
    subtotal: 125.0,
    discountTotal: 0.0,
    taxTotal: 10.0,
    grandTotal: 135.0,
    paidAmount: 150.0,
    changeAmount: 15.0,
    paymentMethod: "cash",
    paymentStatus: "paid",
    status: "completed",
    createdAt: new Date(Date.now() - 42 * 60 * 1000), // 42 mins ago
    updatedAt: new Date(Date.now() - 42 * 60 * 1000),
  },
  {
    _id: "sale_003",
    businessId: "biz_demo_001",
    branchId: "br_colombo_main",
    branchName: "Colombo Main Flagship",
    invoiceNumber: "INV-2026-0410",
    cashierUserId: "usr_cashier_01",
    cashierName: "Kasun Perera",
    customerId: "cust_103",
    customerName: "Nimal Wickramasinghe",
    itemCount: 4,
    items: [],
    subtotal: 890.0,
    discountTotal: 45.0,
    taxTotal: 67.6,
    grandTotal: 912.6,
    paidAmount: 912.6,
    changeAmount: 0.0,
    paymentMethod: "bank_transfer",
    paymentStatus: "paid",
    status: "completed",
    createdAt: new Date(Date.now() - 75 * 60 * 1000), // 1h 15m ago
    updatedAt: new Date(Date.now() - 75 * 60 * 1000),
  },
  {
    _id: "sale_004",
    businessId: "biz_demo_001",
    branchId: "br_kandy",
    branchName: "Kandy Express Branch",
    invoiceNumber: "INV-2026-0409",
    cashierUserId: "usr_cashier_03",
    cashierName: "Saman Jayawardena",
    customerId: "cust_104",
    customerName: "Ruwan Senaratne",
    itemCount: 2,
    items: [],
    subtotal: 210.0,
    discountTotal: 10.0,
    taxTotal: 16.0,
    grandTotal: 216.0,
    paidAmount: 216.0,
    changeAmount: 0.0,
    paymentMethod: "mobile_wallet",
    paymentStatus: "paid",
    status: "completed",
    createdAt: new Date(Date.now() - 110 * 60 * 1000),
    updatedAt: new Date(Date.now() - 110 * 60 * 1000),
  },
  {
    _id: "sale_005",
    businessId: "biz_demo_001",
    branchId: "br_colombo_main",
    branchName: "Colombo Main Flagship",
    invoiceNumber: "INV-2026-0408",
    cashierUserId: "usr_cashier_01",
    cashierName: "Kasun Perera",
    customerId: "cust_105",
    customerName: "Mahesh Jayasuriya",
    itemCount: 6,
    items: [],
    subtotal: 1450.0,
    discountTotal: 100.0,
    taxTotal: 108.0,
    grandTotal: 1458.0,
    paidAmount: 1458.0,
    changeAmount: 0.0,
    paymentMethod: "card",
    paymentStatus: "paid",
    status: "completed",
    createdAt: new Date(Date.now() - 180 * 60 * 1000),
    updatedAt: new Date(Date.now() - 180 * 60 * 1000),
  },
];

export const mockLowStockProducts: InventoryItemSummary[] = [
  {
    productId: "prod_01",
    productName: "Pioneer Double DIN Android Touch Display 9\"",
    sku: "AV-PIO-901",
    categoryName: "Head Units & Audio",
    currentStock: 2,
    lowStockThreshold: 5,
    costPrice: 180.0,
    sellingPrice: 285.0,
    branchId: "br_colombo_main",
    branchName: "Colombo Main",
    isLowStock: true,
  },
  {
    productId: "prod_02",
    productName: "JBL Stage2 6.5\" 2-Way Coaxial Speakers (Pair)",
    sku: "SPK-JBL-S26",
    categoryName: "Speakers",
    currentStock: 1,
    lowStockThreshold: 6,
    costPrice: 42.0,
    sellingPrice: 79.0,
    branchId: "br_colombo_main",
    branchName: "Colombo Main",
    isLowStock: true,
  },
  {
    productId: "prod_03",
    productName: "70mai A800S 4K Dash Cam Front & Rear Set",
    sku: "CAM-70M-A80",
    categoryName: "Dash Cams & Security",
    currentStock: 3,
    lowStockThreshold: 8,
    costPrice: 110.0,
    sellingPrice: 165.0,
    branchId: "br_negombo",
    branchName: "Negombo Auto",
    isLowStock: true,
  },
  {
    productId: "prod_04",
    productName: "Philips Ultinon Pro9000 LED H4 Headlight Bulbs",
    sku: "LGT-PHI-H4P",
    categoryName: "Lighting & LEDs",
    currentStock: 0,
    lowStockThreshold: 4,
    costPrice: 65.0,
    sellingPrice: 115.0,
    branchId: "br_kandy",
    branchName: "Kandy Express",
    isLowStock: true,
  },
  {
    productId: "prod_05",
    productName: "Universal Ceramic Window Tint Film 20% Roll",
    sku: "TNT-CER-20R",
    categoryName: "Window Films",
    currentStock: 2,
    lowStockThreshold: 5,
    costPrice: 85.0,
    sellingPrice: 140.0,
    branchId: "br_colombo_main",
    branchName: "Colombo Main",
    isLowStock: true,
  },
];
